//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeGroup
    {
        public GradeGroup()
        {
            this.Grades = new HashSet<Grade>();
        }
    
        public short GradeGroup1 { get; set; }
        public string GradeGroupName { get; set; }
        public string GradeGroupAName { get; set; }
        public string GradeGroupFName { get; set; }
        public short GradeGroupOrder { get; set; }
        public int GradeGroupCons { get; set; }
        public string GradeGroupNameCons { get; set; }
        public string GradeGroupANameCons { get; set; }
        public string GradeGroupFNameCons { get; set; }
        public Nullable<System.DateTime> GradeGroupFromDate { get; set; }
        public Nullable<System.DateTime> GradeGroupToDate { get; set; }
        public string GradeGroupsRoles { get; set; }
        public string GradeGroupsOrgs { get; set; }
        public short GradeGroupsRYear { get; set; }
        public string GradeGroupsRNo { get; set; }
        public Nullable<System.DateTime> GradeGroupsRIssueDate { get; set; }
        public Nullable<System.DateTime> GradeGroupsRExecDate { get; set; }
        public Nullable<short> GradeGroupsRStatus { get; set; }
        public Nullable<short> GradeGroupsRSource { get; set; }
        public string GradeGroupsRDesc { get; set; }
        public System.Guid GradeGroupsGUID { get; set; }
        public string UEnterBy { get; set; }
        public Nullable<System.DateTime> UEnterDate { get; set; }
        public string UChangeBy { get; set; }
        public Nullable<System.DateTime> UChangeDate { get; set; }
        public string ReviewedBy { get; set; }
        public Nullable<System.DateTime> ReviewedDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> CodeStatus { get; set; }
        public int GradeGroupsOrder { get; set; }
    
        public virtual ICollection<Grade> Grades { get; set; }
    }
}
