//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public short Grade1 { get; set; }
        public string GradeName { get; set; }
        public string GradeAName { get; set; }
        public string GradeFName { get; set; }
        public short GradeYears { get; set; }
        public decimal GradeStepAmount { get; set; }
        public short GradeOrder { get; set; }
        public Nullable<short> GradeGroup { get; set; }
        public short bcount { get; set; }
        public decimal bsalary { get; set; }
        public short level_priv { get; set; }
        public int GradeCons { get; set; }
        public string GradeNameCons { get; set; }
        public string GradeANameCons { get; set; }
        public string GradeFNameCons { get; set; }
        public Nullable<System.DateTime> GradeFromDate { get; set; }
        public Nullable<System.DateTime> GradeToDate { get; set; }
        public string GradesRoles { get; set; }
        public string GradesOrgs { get; set; }
        public short GradesRYear { get; set; }
        public string GradesRNo { get; set; }
        public Nullable<System.DateTime> GradesRIssueDate { get; set; }
        public Nullable<System.DateTime> GradesRExecDate { get; set; }
        public Nullable<short> GradesRStatus { get; set; }
        public Nullable<short> GradesRSource { get; set; }
        public string GradesRDesc { get; set; }
        public System.Guid GradesGUID { get; set; }
        public string UEnterBy { get; set; }
        public Nullable<System.DateTime> UEnterDate { get; set; }
        public string UChangeBy { get; set; }
        public Nullable<System.DateTime> UChangeDate { get; set; }
        public string ReviewedBy { get; set; }
        public Nullable<System.DateTime> ReviewedDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> CodeStatus { get; set; }
        public int GradesOrder { get; set; }
    
        public virtual GradeGroup GradeGroup1 { get; set; }
    }
}
