//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyTable
    {
        public int Grade { get; set; }
        public string GradeName { get; set; }
        public string GradeGroupName { get; set; }
        public Nullable<int> GradeCons { get; set; }
        public string GradeNameCons { get; set; }
    }
}
